# ----------------------------
# Makefile Options
# ----------------------------

NAME = Discord
ICON = icon.png
DESCRIPTION = "Discord"
COMPRESSED = NO
ARCHIVED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
